name: Build UnrealSpeccy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libsdl2-dev

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --parallel

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: unreal-speccy
          path: build/unreal_speccy
